<?php

namespace App\Admin;

use App\Entity\Classe;
use App\Entity\Student;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;
use Sonata\AdminBundle\Templating\TemplateRegistry;
use Symfony\Component\Form\Extension\Core\Type\TextType;

final class ClasseAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper->add('name', TextType::class);

    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper->add('name');
    }

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper->add('name');
        $listMapper->add('_action', 'actions', [
            'actions' => [
                'show' => [],
                'edit' => [],
                'delete' => [],
            ]
        ]);

    }


    protected function configureShowFields(ShowMapper $show)
    {
        $show->add('student',null,[
            'template' => 'Admin/test.html.twig'
            ]);
    }

    /**
     * @param Classe $classe
     */
    public function prePersist($classe)
    {

        parent::prePersist($classe); // TODO: Change the autogenerated stub
        $classe->setCreatedDate(new \DateTime('NOW'));
    }

    /**
     * @param Classe $classe
     */
    public function preUpdate($classe)
    {

        parent::preUpdate($classe); // TODO: Change the autogenerated stub
        $classe->setModifiedDate(new \DateTime('NOW'));
    }


}