<?php

namespace App\Admin;

use App\Entity\Classe;
use App\Entity\Course;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

final class CourseAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper->add('name', TextType::class);
        $formMapper->add('description', TextType::class);
        $formMapper->add('classe', EntityType::class, [
            'class' => Classe::class,
            'choice_label' => function(?Classe $classe){
                return $classe  ? $classe -> getName() : '';
            },
            'multiple' => true,
            'expanded' => true,
            'label' => 'Classes'
        ]);
    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper->add('name');
    }

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper->add('name');
        $listMapper->add('_action','actions', [
            'actions' => [
                'show' => [],
                'edit' => [],
                'delete' => [],
            ]
        ]);
    }

    protected function configureShowFields(ShowMapper $show)
    {
        $show->add('name');
        $show->add('description');
    }

    /**
     * @param Course $course
     */
    public function prePersist($course)
    {

        parent::prePersist($course); // TODO: Change the autogenerated stub
        $course->setCreatedDate(new \DateTime('NOW'));
    }

    /**
     * @param Course $course
     */
    public function preUpdate($course)
    {

        parent::preUpdate($course); // TODO: Change the autogenerated stub
        $course->setModifiedDate(new \DateTime('NOW'));
    }

}