<?php

namespace App\Admin;

use App\Entity\Classe;
use App\Entity\Student;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

final class StudentAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $formMapper)
    {

        $formMapper->add('firstName', TextType::class);
        $formMapper->add('lastName', TextType::class);
        $formMapper->add('dateOfBirth', BirthdayType::class);
        $formMapper->add('classe', EntityType::class, [
            'class' => Classe::class,
            'choice_label' => 'name'
        ]);
        $formMapper->add('gpa',NumberType::class);
    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper->add('firstName');
        $datagridMapper->add('lastName');
        $datagridMapper->add('classe',null, [],EntityType::class,[
            'class' => Classe::class,
            'choice_label' => 'name'
        ]);

    }

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper->add('firstName');
        $listMapper->add('lastName');
        $listMapper->add('_action','actions', [
            'actions' => [
                'show' => [],
                'edit' => [],
                'delete' => [],
            ]
        ]);
    }

    protected function configureShowFields(ShowMapper $show)
    {
        $show->add('firstName');
        $show->add('lastName');
        $show->add('dateOfBirth');
        $show->add('classe.name');
        $show->add('gpa');
    }

    /**
     * @param Student $student
     */
    public function prePersist($student)
    {

        parent::prePersist($student); // TODO: Change the autogenerated stub
        $student->setCreatedDate(new \DateTime('NOW'));
    }

    /**
     * @param Student $student
     */
    public function preUpdate($student)
    {

        parent::preUpdate($student); // TODO: Change the autogenerated stub
        $student->setModifiedDate(new \DateTime('NOW'));
    }



}